export const metadata = {
  title: 'Ecommerce By Lee',
  description: 'Generated by Next.js',
}

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}

